### ISSUE TITLE
Parsing GS1 128 barcode

### ISSUE THREAD

**Issue by Niris1** [Lisi92/cordova-plugin-honeywell-rs-barcode-scanner_ean-transmit#1]
The data result from scanning doesn't include the () or any group separators I'm unable to parse the data in my web application.
Is there a setting i can change that will make the result include the parentheses or group separator..

**Comment by Lisi92** [comment]
Hey Niris, 
you can use the AIM ID to identify whether it is a GS1-128 barcode. For my Honeywell device the GS1-128 AIM IDs are "]C1", "]d1", "]d2". I think it should be the same for you. The barcode you can take from the parameter 'baresult.data' th AIM-ID from 'result.aimId'. If it is one of the 3 Aim IDs you want to decode the GS1-128. 

For the group separator you can use String.fromCharCode(29) 

However, I recommend that you use a ready-made library for decoding. There are quite good ones like https://github.com/PeterBrockfeld/BarcodeParser

Not every AI of the GS1-128 has a separator you can see the definition here https://www.gs1.org/sites/default/files/gs1_general_specifications.pdf (page 143-147)

As an example, AI 01 always has 2 digits as the identifier and 14 digits for the item number. No separator is required here. Only dynamic AIs have separators like the 10 for the batch no. You can see whether an AI has a separator in the column "FNC1 required" .

**Comment by Niris1** [comment]
data 01108479760000401319112010ABC1234
index.js:31 code I
index.js:32 charset ISO-8859-1
index.js:33 aim-id ]C1
index.js:34 timestamp 2024-07-17T06:16:40.870-4:00

my result data looks like this.. The problem is (10)ABC1234 is a batch/lot and its variable in length .As you can see the data has no group separators .Am I scanning wrong barcodes or is something happening with honeywells scanner not showing the group separators?

**Comment by Lisi92** [comment]
The problem with your example is that the separator is not required for the last AI. Try this on
![image](https://github.com/user-attachments/assets/8a574c90-dd6d-426c-a962-86e721af841b)


Then it should be displayed as following
![image](https://github.com/user-attachments/assets/54dc96ee-3fd0-4e94-a830-3b5d69547fa3)

**Comment by Niris1** [comment]
I hope this is it because my brain hurts from researching this...
Thanks for the immediate response and best of wishes!
